# Forsage {#forsage}

- **DApp Homepage:** <https://forsage.io>
- **DApp Source Code:** available on [etherscan.io](https://etherscan.io/address/0x5acc84a3e955Bdd76467d3348077d003f00fFB97#code)
- **ELF Script:** [Forsage.ethql](./elf-scripts/Forsage.ethql)
- **Event Log:** TODO

On their [website](https://forsage.io), the developers of Forsage discribe the DApp as a "Decentralized networking platform based on smart contracts that connects people from all over the world and opens up the limitless possibilities of the new economic financial system".
However, detailed analysis of the DApp's mechanics, e.g., in [1], have shown that the DApp is in fact a Ponzi scheme, i.e., a fraud in which a few early investors generate profits based on the investments of later inverstors (see [Wikipedia](https://en.wikipedia.org/wiki/Ponzi_scheme)).
On [etherscan.io](https://etherscan.io/address/0x5acc84a3e955Bdd76467d3348077d003f00fFB97) the DApp is currently marked as high risk with a note that this DApp is a Ponzi scheme.

## Data Overview

Each trace in the forsage log captures the events from the lifecycle of a Forsage user.
Each trace has the following attributes:

- ``concept:name`` (xs:string) - the address of the Forsage user

In addition, each event has a set of standard attributes:

- ``concept:name`` (xs:string) - The class of the event
- ``time:timestamp`` (xs:date) - The timestamp of the block that included the event
- ``lifecycle:transition`` (xs:string) - The lifecycle transition of each event, for all events set to ``Completed`` by default. This attribute exists to ensure compatibility with [XES-certified tools](https://www.tf-pm.org/resources/xes-standard/for-vendors/certification)
- ``blockNumber`` (xs:int) - The number of the block that included the event
- ``transactionIndex`` (xs:int) - The index of the transaction that included the event
- ``logIndex`` (xs:int) - The index of the log that included the event

The following events can occur during the life of a Forsage user: 

- *Register As User* - The user is registering an account 
  - ``referrer`` (xs:string) - The address of the referring Forsage user
  - ``userId`` (xs:int) - The internal id of the new Forsage user
- *Refer New User* - The user is referring a new user who created an account
  - ``user`` (xs:string) - The address of the new Forsage user
  - ``userId`` (xs:int) - The internal id of the new Forsage user
- *Reinvest Matrix-1* - The user triggers a reinvest
  - ``level`` (xs:int) - The level of the user
  - ``currentReferrer`` (xs:string) - The address of the referrer receiving reinvest. This is the users’s referrer, if it has activated the level receiving the reinvest, otherwise a randomly selected referrer.
  - ``caller`` (xs:string) - The address of user triggering the rein-
vest
- *Reinvest Matrix-2* - The user triggers a reinvest
  - ``level`` (xs:int) - The level of the user
  - ``currentReferrer`` (xs:string) - The address of the referrer receiving reinvest. This is the user’s referrer, if this referrer has activated the level receiving the reinvest, otherwise a randomly selected referrer.
  - ``caller`` (xs:string) - The address of user triggering the reinvest
- *Upgrade Matrix-1* - 
  - ``level`` (xs:int) - 
  - ``referrer`` (xs:string) -
- *Upgrade Matrix-2* - 
  - ``level`` (xs:int) - 
  - ``referrer`` (xs:string) -
- *New User-Place Matrix-1*
  - ``referrer`` (xs:string) -
  - ``level`` (xs:int) - 
  - ``place`` (xs:int) -
- *New User-Place Matrix-2*
  - ``referrer`` (xs:string) -
  - ``level`` (xs:int) - 
  - ``place`` (xs:int) -
- *Missed Eth-Receive Matrix-1* 
  - ``from`` (xs:string) -
  - ``level`` (xs:int) -
- *Missed Eth-Receive Matrix-2* 
  - ``from`` (xs:string) -
  - ``level`` (xs:int) -
- *Received Extra Eth-Dividends Matrix-1* 
  - ``from`` (xs:string) -
  - ``level`` (xs:int) -
- *Recieved Extra Eth-Dividends Matrix-2* 
  - ``from`` (xs:string) -
  - ``level`` (xs:int) -

## Preliminary Analysis

An extensive evaluation of the publicly available Forsage source code was presented in [1] where Kell et al. deployed the Forsage smart contract in a test environment and excercised it with simulated load.
In their analysis, Kell et al. examine the generated event logs in detail, amongst others using a state machine to visualise the behavior of the contract, resulting in an estimation that around 88% of the Forsage users loose their investment, while only a small number of top-level participants is realizing gains.
Complementary to the analysis by Kell et al., we here provide the historic information about the behavior of Forsage users.
 


**References**


[1] T. Kell, H. Yousaf, S. Allen, S. Meiklejohn and A. Juels (2021): "Forsage: Anatomy of a Smart-Contract Pyramid Scheme". <https://arxiv.org/abs/2105.04380>
